import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { SettingsProvider } from "../context/SettingsContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <body
  className={`${geistSans.variable} ${geistMono.variable} antialiased`}
>

  <nav
    style={{
      padding: "20px",
      borderBottom: "1px solid #ccc",
      marginBottom: "20px",
      fontFamily: "sans-serif",
    }}
  >
    <Link href="/" style={{ marginRight: "15px" }}>Dashboard</Link>
    <Link href="/friendship" style={{ marginRight: "15px" }}>Friendship</Link>
    <Link href="/daily" style={{ marginRight: "15px" }}>Daily</Link>
    <Link href="/critters" style={{ marginRight: "15px" }}>Critters</Link>
    <Link href="/inventory" style={{ marginRight: "15px" }}>Inventory</Link>
    <Link href="/turnips" style={{ marginRight: "15px" }}>Turnips</Link>
    <Link href="/backup" style={{ marginRight: "15px" }}>Backup</Link>
    <Link href="/settings">Settings</Link>
    
  </nav>
<SettingsProvider>
  {children}
</SettingsProvider>
</body>
    </html>
  );
}
