import BottomNav from "../components/BottomNav";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { SettingsProvider } from "../context/SettingsContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <body
  className={`${geistSans.variable} ${geistMono.variable} antialiased`}
>
<nav
  style={{
    padding: "18px 24px",
    borderBottom: "1px solid var(--card-border)",
    marginBottom: "24px",
    background: "var(--nav-bg)",
    display: "flex",
    gap: "14px",
    flexWrap: "wrap",
    alignItems: "center",
    boxShadow: "var(--shadow)",
  }}
>
  <Link href="/">Dashboard</Link>
  <Link href="/friendship">Friendship</Link>
  <Link href="/daily">Daily</Link>
  <Link href="/critters">Critters</Link>
  <Link href="/inventory">Inventory</Link>
  <Link href="/turnips">Turnips</Link>
  <Link href="/backup">Backup</Link>
  <Link href="/settings">Settings</Link>
</nav>
<SettingsProvider>
  {children}
  <BottomNav />
</SettingsProvider>
</body>
    </html>
  );
}
